version: '3.8'

services:

  shared_postgresql:
    container_name: keola-code_challenge-shared_postgresql
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ITpg`01M[ls94l7xWD?n94hb0SL|r)
      POSTGRES_DB: backoffice

  shared_mongodb:
    container_name: keola-code_challenge-shared_mongodb
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ITpg`01M[ls94l7xWD?n94hb0SL|r)
      MONGO_INITDB_DATABASE: backoffice
