version: '3.9'

services:
  main:
    labels:
      svc: 'live.postgres'
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: live
    networks:
      - live_backend
      - live_db


networks:
  live_backend:
    name: 'live_backend'
    driver: bridge
  live_db:
    name: 'live_db'
    driver: bridge
