version: '3.9'

services:
  main:
    labels:
      svc: 'live.mongo'
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
        MONGO_INITDB_DATABASE: KeolaDB
    networks:
      - live_backend
      - live_db

networks:
    live_backend:
      external: true
    live_db:
        external: true